//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrumTrainer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class DrumTrainer : global::System.Configuration.ApplicationSettingsBase {
        
        private static DrumTrainer defaultInstance = ((DrumTrainer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DrumTrainer())));
        
        public static DrumTrainer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LatestMidiDevice {
            get {
                return ((int)(this["LatestMidiDevice"]));
            }
            set {
                this["LatestMidiDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MidiSettings {
            get {
                return ((string)(this["MidiSettings"]));
            }
            set {
                this["MidiSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastRefreshToken {
            get {
                return ((string)(this["LastRefreshToken"]));
            }
            set {
                this["LastRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LatestSpotifyDevice {
            get {
                return ((string)(this["LatestSpotifyDevice"]));
            }
            set {
                this["LatestSpotifyDevice"] = value;
            }
        }
    }
}
